### PR TITLE
Nest Thermostat HVAC mode

### PR DESCRIPTION
**Pull request by Corvo**
Nest Thermostat HVAC mode is now supported in flows: a trigger card, a condition card and an action card added.
(also fixed a bug in in the existing HVAC state condition flowcard)

### CODE REVIEW

**Comment by Corvo** [comment]
When changing HVAC modes, the validation is based on the _"special rules around changing `hvac_mode`"_ table found [here](https://developers.nest.com/documentation/cloud/thermostat-guide#hvac-mode-and-temperature-values) in the official documentation.

**Comment by Corvo** [comment]
Tidied up the commits by rebasing.

**Comment by Corvo** [comment]
Commit `	ee3e108` _(Mobile card: Replaced displayed humidty with HVAC-mode picker)_ can be removed if it is undesired.

What this commit does: The humidity value is no longer displayed in the moble/device card, instead an enum picker is presented which the HVAC-mode (which also allows switching it).

Ofcourse humidity can still be used in flows or be spoken by Homey (if asked).

Biggest **downside** to this commit is that a version check forces all devices prior to `2.3.0` te be re-paired, otherwise the `hvac_mode` is an unknown capability.

@RobinBol I assume re-pairing is the only solution, right?
_(at the least, I didn't find any other way to get it to work)_

**Comment by RobinBol** [comment]
Thanks for your work! It is not really desired to remove functionality (humidity in mobile card), as this was requested once by other users. Isn't it possible to display them side by side? The card should become scrollable. The force-re-pair is also not desired, people will have to re-create all their flows with these devices. You could test, installing a device with the current app version in the app store, and then update the app with your improved version to see if it breaks or not, my guess is that everything will just work, except for the newly added capability which will be invisible. But that needs to be tested:)

**Comment by Corvo** [comment]
- Sadly, only the sensor part of the mobile card became scrollable... which looks really weird.
- I did test installing the current version and then upgrading: the result was that de mobile card didn't display any of it's components (cause loading of the `hvac_mode` picker fails since the capability is unknown for the device).

To keep things moving on forward on this, I'd say the best thing to do is to drop [Commit `ee3e108`](https://github.com/athombv/com.nest/pull/32/commits/ee3e108ab53438e6393b8b21a98c9db672ffc503) for now, so the `hvac_mode` support can be integrated.

We can perhaps deliberate the commit and these issues (mobile card & re-pair) on a separate Pull-request?

**Comment by RobinBol** [comment]
Ok that is a pity indeed. I agree with your plan to drop the latest commit. You could put the force-re-pair commits in a separate pull request indeed, but to be honest I don't know if we will merge that anytime soon. Maybe when in the future when we have a more dynamic implementation eliminating the need to re-pair. Would hate to annoy >500 people by forcing them to re-pair their devices and recreate their flows.

**Comment by Corvo** [comment]
As soon as the card does load, even if the capability is missing, we could still look into it. For now I'll just park that commit on a branch. ;)

**Comment by Corvo** [comment]
@RobinBol As agreed upon: the commit was dropped.

**Comment by RobinBol** [comment]
While testing your PR I found the difference between the two flow cards (HVAC state/mode) hard to determine, let alone for less experienced users. Could you add a hint to the new flow card explaining its functionality (and maybe the difference with the HVAC mode)? I could do it for you, but I am not not quite certain about the difference myself:p

**Comment by Corvo** [comment]
Okay, will do that.

FYI, in short: state shows what the current activity is.
Mode indicates what it can/may do.

Is it okay to add a hint to the existing state cards aswell?

**Comment by RobinBol** [comment]
Ok, so if I understand correctly; the mode is basically the capability of the thermostat (which can be set dynamically)?

Adding hints to existing state cards is fine!

**Comment by Corvo** [comment]
If set, the thermostat can even switch itself to Eco if no one is at home.
When the mode is set to "heating" and the measured temperatur is the same as the target temperature, the state will undoubtedly be "off" (it may heat, but it isn't necessary).

When the mode is set to "heating" and the measured temperature is significantly lower than the target temperature, then the state would be "heating".

I hope that clarifies things.

**Comment by Corvo** [comment]
@RobinBol I added hints to both the HVAC state and mode flows cards. I hope this clears things up for anyone confused between the two.
Furthermore, I changed the dutch translation from "HVAC stand" to "HVAV modus" to let it stand out more to "HVAC status".

**Pull request merged**
